document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh-CN\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("	<title>亚洲视频网站</title>");
document.writeln("    <!-- Bootstrap -->");
document.writeln("    <link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css\">");
document.writeln("	<link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico\">");
document.writeln("    <link href=\"http://vjs.zencdn.net/4.12/video-js.css\" rel=\"stylesheet\">");
document.writeln("	<script src=\"http://libs.baidu.com/jquery/2.0.0/jquery.min.js\"></script>");
document.writeln("	<script src=\"http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>");
document.writeln("	<style>");
document.writeln("		body {");
document.writeln("			padding-top: 60px;");
document.writeln("			padding-left: 50px;");
document.writeln("			background:silver;");
document.writeln("		}");
document.writeln("    </style>");
document.writeln("	<!--[if lt IE 9]>");
document.writeln("		<script src=\"http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js\"></script>");
document.writeln("    <![endif]-->");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\"navbar navbar-fixed-top navbar-inverse\" role=\"navigation\">");
document.writeln("	<!--导航栏-->");
document.writeln("		<div class=\"container\">");
document.writeln("			<div class=\"navbar-header\">");
document.writeln("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.writeln("					<span class=\"sr-only\">Toggle navigation</span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("				</button>");
document.writeln("				<div class=\"row\" style=\"left:-20px; position: relative\">");
document.writeln("					<img src=\"/static/AsiaTube.png\" class=\"img-rounded\">");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\"collapse navbar-collapse\">");
document.writeln("			<ul class=\"nav navbar-nav\" id=\"nav_bar\">");
document.writeln("				<li><a id=\"0\"><span class=\"glyphicon glyphicon-home\">主页</span></a></li>");
document.writeln("				<li><a id=\"1\"><span class=\"glyphicon glyphicon-star\">体育</span></a></li>");
document.writeln("				<li><a id=\"2\"><span class=\"glyphicon glyphicon-music\">MV</span></a></li>");
document.writeln("				<li><a id=\"3\"><span class=\"glyphicon glyphicon-film\">电影</span></a></li>");
document.writeln("				<li><a id=\"4\"><span class=\"glyphicon glyphicon-heart-empty\">动漫</span></a></li>");
document.writeln("				<li><a id=\"5\"><span class=\"glyphicon glyphicon-play\">游戏</span></a></li>");
document.writeln("				<li><a id=\"6\"><span class=\"glyphicon glyphicon-plus\">其他鬼畜</span></a></li>");
document.writeln("				");
document.writeln("			</ul>");
document.writeln("            <form class=\"navbar-form navbar-right\" role=\"search\">");
document.writeln("				<button type=\"button\" class=\"btn btn-default\" id=\"SignUp\">注册</button>");
document.writeln("			</form>");
document.writeln("			<form class=\"navbar-form navbar-right\" role=\"search\">");
document.writeln("				<button type=\"button\" class=\"btn btn-primary\" id=\"LogIn\">登录</button>");
document.writeln("			</form>");
document.writeln("			<form id=\"user-option\" class=\"navbar-form nav navbar-nav navbar-right\" role=\"search\">");
document.writeln("				<div class=\"form-group\">");
document.writeln("					<li class=\"dropdown\">");
document.writeln("						<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" style=\"height:44px\"><span id=\"UserName\" class=\"glyphicon glyphicon-user\"><b class=\"caret\"></b></a>");
document.writeln("						<ul class=\"dropdown-menu\">");
document.writeln("							<li><a id=\"UploadVideo\"><font color=\"red\"><b>上传视频</b></font></a></li>");
document.writeln("							<li class=\"divider\"></li>");
document.writeln("							<li><a id=\"ModifyInfo\">修改信息</a></li>");
document.writeln("							<li><a id=\"ModifyPassword\">修改密码</a></li>");
document.writeln("							<li class=\"divider\"></li>");
document.writeln("							<li><a id=\"WatchHistory\">观看历史</a></li>");
document.writeln("							<li><a id=\"UploadHistory\">上传历史</a></li>");
document.writeln("							<li class=\"divider\"></li>");
document.writeln("							<li  id=\"VerifyUser\"><a>审查用户</a></li>");
document.writeln("							<li  id=\"VerifyVideo\"><a>审查视频</a></li>");
document.writeln("							<li class=\"divider\" id = \"Administrator\"></li>");
document.writeln("							<li><a id=\"LogOut\">登出</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</div>");
document.writeln("				<span id=\"UserID\" class=\"label label-default\"></span>");
document.writeln("			</form>  ");
document.writeln("			<form class=\"navbar-form navbar-right\" role=\"search\">");
document.writeln("				<div class=\"form-group\">");
document.writeln("					<input type=\"text\" class=\"form-control\" id=\"searchBar\" placeholder=\"搜索视频...\">");
document.writeln("				</div>");
document.writeln("				<button type=\"button\" class=\"btn btn-default\" id=\"Search\">搜索</button>");
document.writeln("			</form>   ");
document.writeln("			</div><!-- /.nav-collapse -->");
document.writeln("		</div><!-- /.container -->");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");