document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh-CN\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("    <!-- Bootstrap -->");
document.writeln("    <link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css\">");
document.writeln("    <link href=\"http://vjs.zencdn.net/4.12/video-js.css\" rel=\"stylesheet\">");
document.writeln("	<script src=\"http://libs.baidu.com/jquery/2.0.0/jquery.min.js\"></script>");
document.writeln("	<script src=\"http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>");
document.writeln("	<style>");
document.writeln("		body {");
document.writeln("			padding-top: 60px;");
document.writeln("			padding-left: 50px;");
document.writeln("			background:silver;");
document.writeln("		}");
document.writeln("    </style>");
document.writeln("	<!--[if lt IE 9]>");
document.writeln("		<script src=\"http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js\"></script>");
document.writeln("    <![endif]-->");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\"navbar navbar-fixed-top navbar-inverse\" role=\"navigation\">");
document.writeln("	<!--导航栏-->");
document.writeln("		<div class=\"container\">");
document.writeln("			<div class=\"navbar-header\">");
document.writeln("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.writeln("					<span class=\"sr-only\">Toggle navigation</span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("					<span class=\"icon-bar\"></span>");
document.writeln("				</button>");
document.writeln("				<div class=\"row\" style=\"left:-20px; position: relative\">");
document.writeln("					<img src=\"/static/AsiaTube.png\" class=\"img-rounded\">");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\"collapse navbar-collapse\">");
document.writeln("			<ul class=\"nav navbar-nav\">");
document.writeln("				<li class=\"active\"><a href=\"#\" id=\"Home\"><span class=\"glyphicon glyphicon-home\">主页</span></a></li>");
document.writeln("				<li><a href = \"#Game\" id=\"Game\"><span class=\"glyphicon glyphicon-play\">游戏</span></a></li>");
document.writeln("				<li><a href = \"#Movie\" id=\"Movie\"><span class=\"glyphicon glyphicon-film\">电影</span></a></li>");
document.writeln("				<li><a href = \"#Sports\" id=\"Sports\"><span class=\"glyphicon glyphicon-star\">体育</span></a></li>");
document.writeln("				<li><a href = \"#Others\" id=\"Others\"><span class=\"glyphicon glyphicon-plus\">其他</span></a></li>");
document.writeln("			</ul>");
document.writeln("			<form class=\"navbar-form nav navbar-nav navbar-right\" role=\"search\">");
document.writeln("				<div class=\"form-group\">");
document.writeln("					<li class=\"dropdown\">");
document.writeln("						<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" style=\"height:44px\"><span class=\"glyphicon glyphicon-user\">User<b class=\"caret\"></b></a>");
document.writeln("						<ul class=\"dropdown-menu\">");
document.writeln("							<li><a href=\"#\" id=\"ModifyInfo\">修改信息</a></li>");
document.writeln("							<li><a href=\"#\" id=\"ModifyPassword\">修改密码</a></li>");
document.writeln("							<li class=\"divider\"></li>");
document.writeln("							<li><a href=\"#\" id=\"WatchHistory\">观看历史</a></li>");
document.writeln("							<li><a href=\"#\" id=\"UploadHistory\">上传历史</a></li>");
document.writeln("							<li class=\"divider\"></li>");
document.writeln("							<li style=\"display:{{Display}}\"><a href=\"#\" id=\"VerifyUser\">审查用户</a></li>");
document.writeln("							<li style=\"display:{{Display}}\"><a href=\"#\" id=\"VerifyVideo\">审查视频</a></li>");
document.writeln("							<li style=\"display:{{Display}}\"><a href=\"#\" id=\"AdministerType\">编辑类别</a></li>");
document.writeln("							<li class=\"divider\" style=\"display:{{Display}}\"></li>");
document.writeln("							<li><a href=\"#\" id=\"LogOut\">登出</a></li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("				</div>");
document.writeln("				<span class=\"label label-default\">{{UserID}}</span>");
document.writeln("			</form>  ");
document.writeln("			<form class=\"navbar-form navbar-right\" role=\"search\">");
document.writeln("				<div class=\"form-group\">");
document.writeln("					<input type=\"text\" class=\"form-control\" placeholder=\"Search\">");
document.writeln("				</div>");
document.writeln("				<button type=\"submit\" class=\"btn btn-default\" id=\"Search\">搜索</button>");
document.writeln("			</form>   ");
document.writeln("			</div><!-- /.nav-collapse -->");
document.writeln("		</div><!-- /.container -->");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");